import 'dart:math';

import '../../models/enums.dart';
import '../../models/knockout_match.dart';
import '../standings/standings.dart';

class TournamentController {
  static String _shortCode(String roundName) {
    switch (roundName) {
      case 'Play-off':
        return 'PO';
      case 'Round of 16':
        return 'R16';
      case 'Quarter Finals':
        return 'QF';
      case 'Semi Finals':
        return 'SF';
      case 'Final':
        return 'F';
      case '3rd Place':
        return '3P';
      default:
        return 'KO';
    }
  }

  static String _nextRoundName(String current) {
    switch (current) {
      case 'Round of 16':
        return 'Quarter Finals';
      case 'Quarter Finals':
        return 'Semi Finals';
      case 'Semi Finals':
        return 'Final';
      default:
        return '';
    }
  }

  /// Builds a KO tree skeleton from a specified start round (R16/QF/SF/Final).
  /// Wires nextMatchId from each match to the next round match.
  ///
  /// IMPORTANT:
  /// - Third-place matches are NOT generated by default (premium football apps
  ///   typically omit them unless explicitly enabled).
  static List<KnockoutMatch> _buildKnockoutTree({
    required String leagueId,
    required String startRoundName,
    required int startRoundMatchCount,
    required String idPrefix,
    required int nowMs,
    bool includeThirdPlace = false,
  }) {
    String id(String prefix, int index) => '$leagueId-$idPrefix-$prefix-${nowMs}_$index';

    final rounds = <String, List<KnockoutMatch>>{};

    int matchCount = startRoundMatchCount;
    String roundName = startRoundName;

    while (true) {
      final list = <KnockoutMatch>[];
      for (var i = 0; i < matchCount; i++) {
        list.add(
          KnockoutMatch(
            id: id(_shortCode(roundName), i + 1),
            leagueId: leagueId,
            roundName: roundName,
            homeTeamId: null,
            awayTeamId: null,
            homeScore: null,
            awayScore: null,
            status: MatchStatus.scheduled,
            tiebreakWinnerTeamId: null,
            nextMatchId: null,
            loserGoesToMatchId: null,
            isSecondLeg: false,
          ),
        );
      }
      rounds[roundName] = list;

      if (matchCount == 1) break; // Final created

      matchCount = matchCount ~/ 2;
      roundName = _nextRoundName(roundName);
      if (roundName.isEmpty) break;
    }

    // Ordered round names from start to Final.
    final orderedRoundNames = <String>[];
    if (startRoundName == 'Round of 16') {
      orderedRoundNames.addAll(['Round of 16', 'Quarter Finals', 'Semi Finals', 'Final']);
    } else if (startRoundName == 'Quarter Finals') {
      orderedRoundNames.addAll(['Quarter Finals', 'Semi Finals', 'Final']);
    } else if (startRoundName == 'Semi Finals') {
      orderedRoundNames.addAll(['Semi Finals', 'Final']);
    } else if (startRoundName == 'Final') {
      orderedRoundNames.addAll(['Final']);
    }

    // Wire nextMatchId between rounds.
    for (var i = 0; i + 1 < orderedRoundNames.length; i++) {
      final from = List<KnockoutMatch>.from(rounds[orderedRoundNames[i]] ?? const <KnockoutMatch>[]);
      final to = List<KnockoutMatch>.from(rounds[orderedRoundNames[i + 1]] ?? const <KnockoutMatch>[]);

      if (to.isEmpty) continue;

      for (var j = 0; j < from.length; j++) {
        final nextIndex = j ~/ 2;
        if (nextIndex >= to.length) continue;
        from[j] = from[j].copyWith(nextMatchId: to[nextIndex].id);
      }

      rounds[orderedRoundNames[i]] = from;
    }

    // Optional 3rd place if explicitly enabled.
    KnockoutMatch? thirdPlace;
    if (includeThirdPlace && rounds.containsKey('Semi Finals')) {
      thirdPlace = KnockoutMatch(
        id: id('3P', 1),
        leagueId: leagueId,
        roundName: '3rd Place',
        homeTeamId: null,
        awayTeamId: null,
        homeScore: null,
        awayScore: null,
        status: MatchStatus.scheduled,
        tiebreakWinnerTeamId: null,
        nextMatchId: null,
        loserGoesToMatchId: null,
        isSecondLeg: false,
      );

      // Wire semis loser destination.
      final semis = List<KnockoutMatch>.from(rounds['Semi Finals'] ?? const <KnockoutMatch>[]);
      if (semis.isNotEmpty) {
        semis[0] = semis[0].copyWith(loserGoesToMatchId: thirdPlace.id);
      }
      if (semis.length > 1) {
        semis[1] = semis[1].copyWith(loserGoesToMatchId: thirdPlace.id);
      }
      rounds['Semi Finals'] = semis;
    }

    // Flatten output in display order.
    final out = <KnockoutMatch>[];
    for (final rn in orderedRoundNames) {
      out.addAll(rounds[rn] ?? const <KnockoutMatch>[]);
    }
    if (thirdPlace != null) out.add(thirdPlace);

    return out;
  }

  static String _pairKey(String a, String b) => (a.compareTo(b) < 0) ? '$a|$b' : '$b|$a';

  static int _seedIndexFromId(String id) {
    // IDs look like: <league>-<prefix>-<roundCode>-<nowMs>_<index>
    final idx = id.lastIndexOf('_');
    if (idx == -1 || idx + 1 >= id.length) return 0;
    final raw = id.substring(idx + 1);
    return int.tryParse(raw) ?? 0;
  }

  enum _Slot { home, away }

  /// Determines which slot (home/away) this match must feed into on its next match.
  ///
  /// Root cause fixed:
  /// Previously we were "fill first null slot", which is NOT idempotent:
  /// re-saving the same semifinal would fill home on first save, then away on second save,
  /// producing duplicate finalists (A vs A).
  static _Slot _slotForAdvancement({
    required KnockoutMatch fromMatch,
    required List<KnockoutMatch> allMatches,
  }) {
    final nextId = fromMatch.nextMatchId;
    if (nextId == null) return _Slot.home;

    // All matches from the SAME round that advance into the SAME next match.
    final feeders = allMatches
        .where((m) => m.roundName == fromMatch.roundName && m.nextMatchId == nextId)
        .toList();

    if (feeders.length <= 1) {
      // Single feeder (rare, but possible with byes or special formats).
      // Always write to HOME to keep idempotency (overwrite same slot).
      return _Slot.home;
    }

    feeders.sort((a, b) {
      final ai = _seedIndexFromId(a.id);
      final bi = _seedIndexFromId(b.id);
      if (ai != bi) return ai.compareTo(bi);
      return a.id.compareTo(b.id);
    });

    final pos = feeders.indexWhere((m) => m.id == fromMatch.id);
    final safePos = max(0, pos);
    return (safePos % 2 == 0) ? _Slot.home : _Slot.away;
  }

  static List<KnockoutMatch> _advanceWinnerToNext({
    required KnockoutMatch completedMatch,
    required String winnerId,
    required List<KnockoutMatch> allMatches,
  }) {
    final nextId = completedMatch.nextMatchId;
    if (nextId == null) return allMatches;

    final slot = _slotForAdvancement(fromMatch: completedMatch, allMatches: allMatches);

    return allMatches.map((m) {
      if (m.id != nextId) return m;
      // Overwrite ONLY the deterministic slot -> idempotent + supports corrections.
      return switch (slot) {
        _Slot.home => m.copyWith(homeTeamId: winnerId),
        _Slot.away => m.copyWith(awayTeamId: winnerId),
      };
    }).toList();
  }

  static List<KnockoutMatch> _placeLoserToThirdPlace({
    required KnockoutMatch completedSemiFinal,
    required String loserId,
    required List<KnockoutMatch> allMatches,
  }) {
    final thirdId = completedSemiFinal.loserGoesToMatchId;
    if (thirdId == null) return allMatches;

    // Determine which slot the loser should fill based on semi-final ordering.
    final semiFeeders = allMatches
        .where((m) => m.roundName == 'Semi Finals' && m.loserGoesToMatchId == thirdId)
        .toList();

    if (semiFeeders.isEmpty) return allMatches;

    semiFeeders.sort((a, b) {
      final ai = _seedIndexFromId(a.id);
      final bi = _seedIndexFromId(b.id);
      if (ai != bi) return ai.compareTo(bi);
      return a.id.compareTo(b.id);
    });

    final pos = semiFeeders.indexWhere((m) => m.id == completedSemiFinal.id);
    final safePos = max(0, pos);
    final slot = (safePos % 2 == 0) ? _Slot.home : _Slot.away;

    return allMatches.map((m) {
      if (m.id != thirdId) return m;
      return switch (slot) {
        _Slot.home => m.copyWith(homeTeamId: loserId),
        _Slot.away => m.copyWith(awayTeamId: loserId),
      };
    }).toList();
  }

  /// UCL GROUP MODEL:
  /// - Allowed total teams: 16 or 32
  /// - Structure: groups of 4
  ///   - 16 teams => 4 groups of 4 => top 2 => 8 qualifiers => Quarter Finals start
  ///   - 32 teams => 8 groups of 4 => top 2 => 16 qualifiers => Round of 16 start
  ///
  /// This method enforces:
  /// - number of groups must be 4 or 8
  /// - each group standings list must have exactly 4 teams
  static List<KnockoutMatch> seedKnockoutsFromGroups({
    required String leagueId,
    required Map<String, List<StandingsRow>> groupStandings,
  }) {
    if (groupStandings.isEmpty) return [];

    final now = DateTime.now().millisecondsSinceEpoch;

    final keys = groupStandings.keys.toList()..sort();
    final groupCount = keys.length;

    if (groupCount != 4 && groupCount != 8) return [];

    // Enforce each group has exactly 4 teams ranked.
    for (final k in keys) {
      final rows = groupStandings[k] ?? const <StandingsRow>[];
      if (rows.length != 4) return [];
      if (rows.length < 2) return [];
    }

    final winners = <StandingsRow>[for (final k in keys) groupStandings[k]![0]];
    final runners = <StandingsRow>[for (final k in keys) groupStandings[k]![1]];

    final startRoundName = (groupCount == 8) ? 'Round of 16' : 'Quarter Finals';
    final startMatchCount = (groupCount == 8) ? 8 : 4;

    final tree = _buildKnockoutTree(
      leagueId: leagueId,
      startRoundName: startRoundName,
      startRoundMatchCount: startMatchCount,
      idPrefix: 'GRP',
      nowMs: now,
      includeThirdPlace: false,
    );

    final startRound = tree.where((m) => m.roundName == startRoundName).toList();
    if (startRound.length != startMatchCount) return [];

    // Pair groups in twos: (A,B), (C,D), ...:
    // A1 vs B2, B1 vs A2, etc.
    final seeded = <KnockoutMatch>[];
    var idx = 0;
    for (var i = 0; i + 1 < winners.length; i += 2) {
      final g1Winner = winners[i];
      final g2Winner = winners[i + 1];
      final g1Runner = runners[i];
      final g2Runner = runners[i + 1];

      seeded.add(
        startRound[idx++].copyWith(
          homeTeamId: g1Winner.teamId,
          awayTeamId: g2Runner.teamId,
        ),
      );
      seeded.add(
        startRound[idx++].copyWith(
          homeTeamId: g2Winner.teamId,
          awayTeamId: g1Runner.teamId,
        ),
      );
    }

    final seededById = {for (final m in seeded) m.id: m};
    return tree.map((m) => seededById[m.id] ?? m).toList();
  }

  /// UCL SWISS MODEL:
  /// - Allowed total teams: 18 or 36
  /// - League phase standings must include exactly that many teams.
  /// - Play-off is two-legged (aggregate over 2 legs).
  ///
  /// For 36 teams (UEFA-style):
  /// - Top 8 -> Round of 16 (home slots)
  /// - 9–24 -> Play-off (16 teams => 8 ties => 16 matches / 2 legs)
  /// - 25–36 eliminated
  ///
  /// For 18 teams (compact variant):
  /// - Top 4 -> Quarter Finals (home slots)
  /// - 5–12 -> Play-off (8 teams => 4 ties => 8 matches / 2 legs)
  /// - 13–18 eliminated
  static List<KnockoutMatch> seedSwissKnockouts({
    required String leagueId,
    required List<StandingsRow> swissStandings,
  }) {
    final n = swissStandings.length;

    if (n != 36 && n != 18) return [];

    final now = DateTime.now().millisecondsSinceEpoch;
    String id(String prefix, int index) => '$leagueId-SWISS-$prefix-${now}_$index';

    if (n == 36) {
      final autoQualifiers = swissStandings.take(8).toList(); // 1–8
      final playoffSeeds = swissStandings.skip(8).take(16).toList(); // 9–24
      if (playoffSeeds.length != 16) return [];

      final tree = _buildKnockoutTree(
        leagueId: leagueId,
        startRoundName: 'Round of 16',
        startRoundMatchCount: 8,
        idPrefix: 'SWISS',
        nowMs: now,
        includeThirdPlace: false,
      );

      final r16 = tree.where((m) => m.roundName == 'Round of 16').toList();
      if (r16.length != 8) return [];

      // Seed Top 8 as home teams.
      final seededR16 = <KnockoutMatch>[];
      for (var i = 0; i < 8; i++) {
        seededR16.add(
          r16[i].copyWith(
            homeTeamId: autoQualifiers[i].teamId,
            awayTeamId: null, // filled by playoff winners
          ),
        );
      }

      // Create 8 two-legged ties: 9 vs 24, 10 vs 23, ... 16 vs 17
      final playoffMatches = <KnockoutMatch>[];
      int start = 0;
      int end = playoffSeeds.length - 1;

      for (var tieIndex = 0; tieIndex < 8; tieIndex++) {
        final a = playoffSeeds[start++]; // higher seed in PO pool
        final b = playoffSeeds[end--]; // lower seed
        final r16Index = 7 - tieIndex;

        // Leg 1
        playoffMatches.add(
          KnockoutMatch(
            id: id('PO1', tieIndex + 1),
            leagueId: leagueId,
            roundName: 'Play-off',
            homeTeamId: a.teamId,
            awayTeamId: b.teamId,
            homeScore: null,
            awayScore: null,
            status: MatchStatus.scheduled,
            tiebreakWinnerTeamId: null,
            nextMatchId: seededR16[r16Index].id,
            loserGoesToMatchId: null,
            isSecondLeg: false,
          ),
        );

        // Leg 2 (reverse)
        playoffMatches.add(
          KnockoutMatch(
            id: id('PO2', tieIndex + 1),
            leagueId: leagueId,
            roundName: 'Play-off',
            homeTeamId: b.teamId,
            awayTeamId: a.teamId,
            homeScore: null,
            awayScore: null,
            status: MatchStatus.scheduled,
            tiebreakWinnerTeamId: null,
            nextMatchId: seededR16[r16Index].id,
            loserGoesToMatchId: null,
            isSecondLeg: true,
          ),
        );
      }

      final seededById = {for (final m in seededR16) m.id: m};
      final updatedTree = tree.map((m) => seededById[m.id] ?? m).toList();

      return [
        ...playoffMatches,
        ...updatedTree,
      ];
    }

    // n == 18
    final autoQualifiers = swissStandings.take(4).toList(); // 1–4
    final playoffSeeds = swissStandings.skip(4).take(8).toList(); // 5–12
    if (playoffSeeds.length != 8) return [];

    final tree = _buildKnockoutTree(
      leagueId: leagueId,
      startRoundName: 'Quarter Finals',
      startRoundMatchCount: 4,
      idPrefix: 'SWISS',
      nowMs: now,
      includeThirdPlace: false,
    );

    final qf = tree.where((m) => m.roundName == 'Quarter Finals').toList();
    if (qf.length != 4) return [];

    // Seed Top 4 as home teams in QF.
    final seededQF = <KnockoutMatch>[];
    for (var i = 0; i < 4; i++) {
      seededQF.add(
        qf[i].copyWith(
          homeTeamId: autoQualifiers[i].teamId,
          awayTeamId: null, // filled by playoff winners
        ),
      );
    }

    // Create 4 two-legged ties: 5 vs 12, 6 vs 11, 7 vs 10, 8 vs 9
    final playoffMatches = <KnockoutMatch>[];
    int start = 0;
    int end = playoffSeeds.length - 1;

    for (var tieIndex = 0; tieIndex < 4; tieIndex++) {
      final a = playoffSeeds[start++];
      final b = playoffSeeds[end--];
      final qfIndex = 3 - tieIndex;

      playoffMatches.add(
        KnockoutMatch(
          id: id('PO1', tieIndex + 1),
          leagueId: leagueId,
          roundName: 'Play-off',
          homeTeamId: a.teamId,
          awayTeamId: b.teamId,
          homeScore: null,
          awayScore: null,
          status: MatchStatus.scheduled,
          tiebreakWinnerTeamId: null,
          nextMatchId: seededQF[qfIndex].id,
          loserGoesToMatchId: null,
          isSecondLeg: false,
        ),
      );

      playoffMatches.add(
        KnockoutMatch(
          id: id('PO2', tieIndex + 1),
          leagueId: leagueId,
          roundName: 'Play-off',
          homeTeamId: b.teamId,
          awayTeamId: a.teamId,
          homeScore: null,
          awayScore: null,
          status: MatchStatus.scheduled,
          tiebreakWinnerTeamId: null,
          nextMatchId: seededQF[qfIndex].id,
          loserGoesToMatchId: null,
          isSecondLeg: true,
        ),
      );
    }

    final seededById = {for (final m in seededQF) m.id: m};
    final updatedTree = tree.map((m) => seededById[m.id] ?? m).toList();

    return [
      ...playoffMatches,
      ...updatedTree,
    ];
  }

  /// Automatic advancement after a KO match is confirmed.
  ///
  /// Special rule:
  /// - For two-legged "Play-off" ties, advancement happens ONLY when the
  ///   second leg is completed, using aggregate score across both legs.
  /// - If aggregate is tied after leg 2, completedMatch.tiebreakWinnerTeamId is required.
  static List<KnockoutMatch> processMatchResult({
    required KnockoutMatch completedMatch,
    required List<KnockoutMatch> allMatches,
  }) {
    if (!completedMatch.isFinished) return allMatches;

    // Two-legged Play-off aggregate handling
    if (completedMatch.roundName == 'Play-off') {
      if (!completedMatch.isSecondLeg) return allMatches;

      final hId = completedMatch.homeTeamId;
      final aId = completedMatch.awayTeamId;
      if (hId == null || aId == null) return allMatches;

      final nextId = completedMatch.nextMatchId;
      if (nextId == null) return allMatches;

      final tieKey = _pairKey(hId, aId);

      KnockoutMatch? firstLeg;
      for (final m in allMatches) {
        if (m.roundName != 'Play-off') continue;
        if (m.isSecondLeg) continue;
        if (m.nextMatchId != nextId) continue;
        if (m.homeTeamId == null || m.awayTeamId == null) continue;
        if (_pairKey(m.homeTeamId!, m.awayTeamId!) != tieKey) continue;
        firstLeg = m;
        break;
      }

      if (firstLeg == null) return allMatches;
      if (!firstLeg.isFinished) return allMatches;

      final totals = <String, int>{hId: 0, aId: 0};

      void add(KnockoutMatch m) {
        final home = m.homeTeamId!;
        final away = m.awayTeamId!;
        totals[home] = (totals[home] ?? 0) + m.homeScore!;
        totals[away] = (totals[away] ?? 0) + m.awayScore!;
      }

      add(firstLeg);
      add(completedMatch);

      final hTot = totals[hId] ?? 0;
      final aTot = totals[aId] ?? 0;

      String? winner;
      if (hTot > aTot) {
        winner = hId;
      } else if (aTot > hTot) {
        winner = aId;
      } else {
        winner = completedMatch.tiebreakWinnerTeamId; // penalties on leg 2
      }

      if (winner == null) return allMatches;

      // For play-offs, we place the winner into the "available" slot.
      // If both are filled (e.g., after edits), we overwrite AWAY (UEFA-style: seeded teams are usually HOME).
      return allMatches.map((m) {
        if (m.id != nextId) return m;

        final nextHome = m.homeTeamId;
        final nextAway = m.awayTeamId;

        if (nextHome == null && nextAway != null) return m.copyWith(homeTeamId: winner);
        if (nextAway == null && nextHome != null) return m.copyWith(awayTeamId: winner);
        if (nextHome == null && nextAway == null) return m.copyWith(homeTeamId: winner);

        // both filled -> overwrite away to be deterministic
        if (nextAway != winner) return m.copyWith(awayTeamId: winner);
        return m;
      }).toList();
    }

    // Standard single-match advancement for R16/QF/SF/Final
    final winnerId = completedMatch.winnerTeamId;
    if (winnerId == null) return allMatches;

    final loserId = (winnerId == completedMatch.homeTeamId) ? completedMatch.awayTeamId : completedMatch.homeTeamId;

    var updated = allMatches;

    // Winner advances (IDEMPOTENT + CORRECTION-SAFE).
    if (completedMatch.nextMatchId != null) {
      updated = _advanceWinnerToNext(
        completedMatch: completedMatch,
        winnerId: winnerId,
        allMatches: updated,
      );
    }

    // Optional 3rd place placement (only if loserGoesToMatchId exists).
    if (loserId != null && completedMatch.roundName == 'Semi Finals' && completedMatch.loserGoesToMatchId != null) {
      updated = _placeLoserToThirdPlace(
        completedSemiFinal: completedMatch,
        loserId: loserId,
        allMatches: updated,
      );
    }

    return updated;
  }
}
