'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { QRCodeSVG } from 'qrcode.react';
import { auth, db } from '@/lib/firebase';
import { doc, onSnapshot, setDoc, serverTimestamp } from 'firebase/firestore';
import { signInWithCustomToken } from 'firebase/auth';
import { setCookie } from 'cookies-next';
import { Glass } from '@/components/ui/Glass';
import { GlassScaffold } from '@/components/ui/GlassScaffold';
import { Loader2, MonitorSmartphone, QrCode } from 'lucide-react';

export default function WebPairingScreen() {
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [status, setStatus] = useState<'generating' | 'waiting' | 'approved' | 'failed'>('generating');
  const router = useRouter();

  useEffect(() => {
    // 1. Generate a unique desktop session ID
    const generateSession = async () => {
      try {
        const newSessionId = crypto.randomUUID().replace(/-/g, '').substring(0, 16);
        
        // Write the pending session to Firestore (mimicking your Supabase/Firestore session store)
        await setDoc(doc(db, 'desktop_sessions', newSessionId), {
          status: 'pending',
          createdAt: serverTimestamp(),
          deviceInfo: navigator.userAgent,
        });

        setSessionId(newSessionId);
        setStatus('waiting');
      } catch (error) {
        console.error("Failed to generate session", error);
        setStatus('failed');
      }
    };

    generateSession();
  }, []);

  useEffect(() => {
    if (!sessionId) return;

    // 2. Listen to Firestore for the mobile app to approve the session
    const unsubscribe = onSnapshot(doc(db, 'desktop_sessions', sessionId), async (docSnap) => {
      if (docSnap.exists()) {
        const data = docSnap.data();
        
        if (data.status === 'approved' && data.customToken) {
          setStatus('approved');
          try {
            // 3. Log the web client in automatically using the token generated by the mobile app
            const userCredential = await signInWithCustomToken(auth, data.customToken);
            const token = await userCredential.user.getIdToken();
            
            // Set Next.js session cookie
            setCookie('session', token, { maxAge: 60 * 60 * 24 * 5 });
            
            // Redirect to dashboard
            router.push('/leagues');
          } catch (error) {
            console.error("Failed to sign in with token", error);
            setStatus('failed');
          }
        }
      }
    });

    return () => unsubscribe();
  }, [sessionId, router]);

  return (
    <GlassScaffold>
      <div className="flex flex-col items-center justify-center min-h-[85vh] p-4">
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-brand-lime/10 border border-brand-lime/30 mb-6">
            <MonitorSmartphone className="w-8 h-8 text-brand-lime" />
          </div>
          <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight">Desktop Pairing</h1>
          <p className="text-gray-400 mt-3 max-w-md mx-auto">
            Scan this QR code with the eSportlyic mobile app to instantly sign in on this device.
          </p>
        </div>

        <Glass intensity="high" className="p-8 md:p-12 flex flex-col items-center">
          {status === 'generating' ? (
            <div className="w-64 h-64 flex flex-col items-center justify-center gap-4 bg-brand-surface border border-white/5 rounded-2xl">
              <Loader2 className="w-8 h-8 text-brand-lime animate-spin" />
              <p className="text-sm font-medium text-gray-400">Generating secure session...</p>
            </div>
          ) : status === 'failed' ? (
            <div className="w-64 h-64 flex flex-col items-center justify-center gap-4 bg-brand-red/10 border border-brand-red/30 rounded-2xl text-center p-4">
              <p className="text-brand-red font-bold">Session Failed</p>
              <p className="text-sm text-gray-400">Please refresh the page to try again.</p>
              <button 
                onClick={() => window.location.reload()}
                className="mt-2 px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-sm text-white transition-colors"
              >
                Refresh
              </button>
            </div>
          ) : (
            <div className="relative group">
              <div className="absolute -inset-1 bg-gradient-to-r from-brand-lime to-[#38BDF8] rounded-3xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200" />
              <div className="relative bg-white p-4 rounded-2xl">
                {sessionId && (
                  <QRCodeSVG 
                    value={JSON.stringify({ type: 'desktop_pairing', sessionId })} 
                    size={240}
                    bgColor={"#ffffff"}
                    fgColor={"#081120"}
                    level={"H"}
                    includeMargin={false}
                  />
                )}
              </div>
            </div>
          )}

          <div className="mt-8 text-center space-y-4">
            {status === 'waiting' && (
              <div className="flex items-center justify-center gap-2 text-brand-lime">
                <span className="relative flex h-3 w-3">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-lime opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-brand-lime"></span>
                </span>
                <span className="font-semibold text-sm">Waiting for mobile scan...</span>
              </div>
            )}
            
            {status === 'approved' && (
              <div className="text-green-400 font-bold flex items-center justify-center gap-2">
                <span>Pairing successful! Redirecting...</span>
              </div>
            )}

            <div className="pt-6 border-t border-white/10 w-full mt-4">
              <p className="text-xs text-gray-500">Don't have your phone handy?</p>
              <button 
                onClick={() => router.push('/login')}
                className="mt-2 text-sm text-brand-lime hover:underline font-medium"
              >
                Sign in with Email & Password instead
              </button>
            </div>
          </div>
        </Glass>
      </div>
    </GlassScaffold>
  );
}
